apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws-power-controller
  labels:
    app: aws-power-controller
  namespace: spaceone
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aws-power-controller
      domain_id: domain-dc2ad7d78a19
      plugin_name: aws-power-controller
      service_type: power_scheduler.Controller
      supervisor_name: root
      version: '1.0'
  template:
    metadata:
      labels:
        app: aws-power-controller
        domain_id: domain-dc2ad7d78a19
        plugin_name: aws-power-controller
        service_type: power_scheduler.Controller
        supervisor_name: root
        version: '1.0'
    spec:
      containers:
      - name: aws-power-controller
        image: 110365492710.dkr.ecr.ap-northeast-2.amazonaws.com/spaceone/aws-power-controller:latest
        ports:
        - containerPort: 50051
          protocol: TCP
