apiVersion: skaffold/v2beta2
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.SKAFFOLD_TAG}}"
  artifacts:
    - image: 110365492710.dkr.ecr.ap-northeast-2.amazonaws.com/spaceone/aws-power-controller
      context: ./
deploy:
  kubectl:
    manifests:
      - ./deployments.yml